apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: e-commerce-microservice
build:
  artifacts:
    - image: product-service
      context: services/product-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*
            dest: /usr/src/app/src  # Sync only relevant files
    - image: elastic-service
      context: services/elastic-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*
            dest: /usr/src/app/src
manifests:
  rawYaml:
    - kubernetes/base/**/*.yaml
    - kubernetes/overlays/**/**/*.yaml
portForward:
  - resourceType: deployment
    resourceName: product-deployment
    port: 3000
    localPort: 3000
  - resourceType: StatefulSet
    resourceName: product-mongo-dp
    port: 27017
    localPort: 27017
profiles:
  - name: dev
    build:
      artifacts:
        - image: product-service
          context: services/product-service
          sync:
            manual:
              - src: src/**/*.ts
                dest: /usr/src/app/src  # Only sync .ts files for development
        - image: elastic-service
          context: services/elastic-service
          sync:
            manual:
              - src: src/**/*.ts
                dest: /usr/src/app/src
