apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: e-commerce-microservice
build:
  artifacts:
    - image: product-service
      context: services/product-service
manifests:
  rawYaml:
    - kubernetes/base/**/*.yaml
    - kubernetes/overlays/**/**/*.yaml
portForward:
  - resourceType: deployment
    resourceName: product-deployment
    port: 3000
    localPort: 3000
  - resourceType: StatefulSet
    resourceName: product-mongo-dp
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: elasticsearch-es-http
    namespace: default
    port: 9200
    localPort: 9200
  - resourceType: service
    resourceName: kibana-kb-http
    namespace: default
    port: 5601
    localPort: 5601
profiles:
  - name: dev
    build:
      artifacts:
        - image: product-service
          context: services/product-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: services/product-service/Dockerfile
    portForward:
      - resourceType: service
        resourceName: product-svc
        port: 3000
        localPort: 3000
      - resourceType: service
        resourceName: product-mongo-svc
        port: 27017
        localPort: 27017