apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-deployment
  template:
    metadata:
      labels:
        app: product-deployment
    spec:
      containers:
        - name: product-deployment
          image: product-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: product-service-configmap
            - secretRef:
                name: product-service-secret
          ports:
            - containerPort: 3000
      serviceAccountName: product-sa
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-mongo-dp
  namespace: default
spec:
  serviceName: "product-mongo-svc"
  replicas: 2
  selector:
    matchLabels:
      role: database
      app: product-mongo-dp
  template:
    metadata:
      labels:
        role: database
        app: product-mongo-dp
    spec:
      containers:
        - name: product-mongo-dp
          image: mongo:latest
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - |
              mongod --replSet rs0 --bind_ip_all --port 27017 &
              sleep 10
              mongosh --host product-mongo-svc:27017 --eval "rs.status()" || mongosh --host product-mongo-svc:27017 --eval 'rs.initiate()'
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/data/db"
              name: product-mongo-storage
  volumeClaimTemplates:
    - metadata:
        name: product-mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
