apiVersion: v1
kind: Service
metadata:
  name: elastic-svc
  namespace: default
  labels:
    app: elastic-deployment
spec:
  selector:
    app: elastic-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3001
  type: ClusterIP