apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: db-access-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-access-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: product-sa
    namespace: default
roleRef:
  kind: Role
  name: db-access-role
  apiGroup: rbac.authorization.k8s.io
